import { Tags } from "npm:@digibear/tags@1.0.0"
import { Parser } from "npm:@ursamu/parser@1.2.4"
import { compare, hash } from "npm:bcryptjs@2.4.3"
import { config } from "npm:dotenv@16.3.1"
import { NextFunction, Request, Response, Router, express } from "npm:express-svelte@1.0.8"
import { jwt } from "npm:jsonwebtoken@9.0.1"
import { set, get, isnumber, repeat } from "npm:lodash@4.17.21"
import { Datastore } from "npm:nedb-promises@6.2.1"
import { Socket, Server } from "npm:socket.io@4.7.1"
import { io } from "npm:socket.io-client@4.7.1"
import { VM } from "npm:vm2@3.9.19"
