import { get } from "../../deps.ts";
import { IDBOBJ, IMStat } from "../../src/@types/index.ts";
import { Obj } from "../../src/services/DBObjs/index.ts";
import { getStat } from "../../src/services/characters/getStats.ts";

export const disciplines: IMStat[] = [
  {
    name: "Animalism",
    type: "discipline",
    values: [1, 2, 3, 4, 5],
    hasSpecialties: true,
    splat: ["vampire"],
    error: "You must be a vampire.",
    specialties: [
      {
        name: "bond famulus",
        type: "animalism",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Animalism to take this power.",
      },
      {
        name: "sense the beast",
        type: "animalism",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Animalism to take this power.",
      },
      {
        name: "feral whispers",
        type: "animalism",
        values: [2],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 2,
        splat: ["vampire"],
        error: "You must have at least 2 dots in Animalism to take this power.",
      },
      {
        name: "animal succulence",
        type: "animalism",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dots in Animalism to take this power.",
      },
      {
        name: "quell the beast",
        type: "animalism",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dots in Animalism to take this power.",
      },
      {
        name: "unliving hive",
        type: "animalism",
        values: [3],
        check: async (obj: Obj) =>
          (await getStat(obj, "animalism")) >= 3 &&
          (await getStat(obj, "obfuscate")) >= 2,
        splat: ["vampire"],
        error:
          "You must have at least 3 dots in Animalism and 2 dots in Obfuscate to take this power.",
      },
      {
        name: "subsume the spirit",
        type: "animalism",
        values: [4],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 4,
        splat: ["vampire"],
        error: "You must have at least 4 dots in Animalism to take this power.",
      },
      {
        name: "animal dominion",
        type: "animalism",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dots in Animalism to take this power.",
      },
      {
        name: "drawing out the beast",
        type: "animalism",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "animalism")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dots in Animalism to take this power.",
      },
    ],
  },
  {
    name: "Auspex",
    type: "discipline",
    values: [1, 2, 3, 4, 5],
    hasSpecialties: true,
    splat: ["vampire"],
    error: "You must be a vampire.",
    specialties: [
      {
        name: "heightened senses",
        type: "auspex",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Auspex to take this power.",
      },
      {
        name: "sense the unseen",
        type: "auspex",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Auspex to take this power.",
      },
      {
        name: "premonition",
        type: "auspex",
        values: [2],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 2,
        splat: ["vampire"],
        error: "You must have at least 2 dots in Auspex to take this power.",
      },
      {
        name: "scry the soul",
        type: "auspex",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dots in Auspex to take this power.",
      },
      {
        name: "share the senses",
        type: "auspex",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dots in Auspex to take this power.",
      },
      {
        name: "spirits touch",
        type: "auspex",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dots in Auspex to take this power.",
      },
      {
        name: "clairvoyance",
        type: "auspex",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dots in Auspex to take this power.",
      },
      {
        name: "posession",
        type: "auspex",
        values: [5],
        check: async (obj: Obj) =>
          (await getStat(obj, "auspex")) >= 5 &&
          (await getStat(obj, "dominate")) >= 3,
        splat: ["vampire"],
        error:
          "You must have at least 5 dots in Auspex and 3 dots in Dominate to take this power.",
      },
      {
        name: "telepathy",
        type: "auspex",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "auspex")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dots in Auspex to take this power.",
      },
    ],
  },
  {
    name: "Celerity",
    type: "discipline",
    values: [1, 2, 3, 4, 5],
    hasSpecialties: true,
    splat: ["vampire"],
    error: "You must be a vampire.",
    specialties: [
      {
        name: "cats grace",
        type: "celerity",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Celerity to take this power.",
      },
      {
        name: "rapid reflexes",
        type: "celerity",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Celerity to take this power.",
      },
      {
        name: "fleetness",
        type: "celerity",
        values: [2],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 2,
        splat: ["vampire"],
        error: "You must have at least 2 dot in Celerity to take this power.",
      },
      {
        name: "blink",
        type: "celerity",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dot in Celerity to take this power.",
      },
      {
        name: "traversal",
        type: "celerity",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dot in Celerity to take this power.",
      },
      {
        name: "draught of elegance",
        type: "celerity",
        values: [4],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 4,
        splat: ["vampire"],
        error: "You must have at least 4 dot in Celerity to take this power.",
      },
      {
        name: "unerring aim",
        type: "celerity",
        values: [4],
        check: async (obj: Obj) =>
          (await getStat(obj, "celerity")) >= 4 &&
          (await getStat(obj, "auspex")) >= 3,
        splat: ["vampire"],
        error:
          "You must have at least 4 dot in Celerity and 3 dot in Auspex to take this power.",
      },
      {
        name: "lightning strike",
        type: "celerity",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dot in Celerity to take this power.",
      },
      {
        name: "split second",
        type: "celerity",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "celerity")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dot in Celerity to take this power.",
      },
    ],
  },
  {
    name: "dominate",
    type: "discipline",
    values: [1, 2, 3, 4, 5],
    hasSpecialties: true,
    splat: ["vampire"],
    error: "You must be a vampire.",
    specialties: [
      {
        name: "cloud memory",
        type: "dominate",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Dominate to take this power.",
      },
      {
        name: "compell",
        type: "dominate",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Dominate to take this power.",
      },
      {
        name: "mesmerize",
        type: "dominate",
        values: [2],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 2,
        splat: ["vampire"],
        error: "You must have at least 2 dot in Dominate to take this power.",
      },
      {
        name: "dementation",
        type: "dominate",
        values: [2],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 2,
        splat: ["vampire"],
        error: "You must have at least 2 dot in Dominate to take this power.",
      },
      {
        name: "the forgetful mind",
        type: "dominate",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dot in Dominate to take this power.",
      },
      {
        name: "submerged directive",
        type: "dominate",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dot in Dominate to take this power.",
      },
      {
        name: "rationalize",
        type: "dominate",
        values: [4],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 4,
        splat: ["vampire"],
        error: "You must have at least 4 dot in Dominate to take this power.",
      },
      {
        name: "mass manipulation",
        type: "dominate",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dot in Dominate to take this power.",
      },
      {
        name: "terminal decree",
        type: "dominate",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "dominate")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dot in Dominate to take this power.",
      },
    ],
  },
  {
    name: "Fortitude",
    type: "discipline",
    values: [1, 2, 3, 4, 5],
    hasSpecialties: true,
    splat: ["vampire"],
    error: "You must be a vampire.",
    specialties: [
      {
        name: "resilience",
        type: "fortitude",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Fortitude to take this power.",
      },
      {
        name: "unswayable mind",
        type: "fortitude",
        values: [1],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 1,
        splat: ["vampire"],
        error: "You must have at least 1 dot in Fortitude to take this power.",
      },
      {
        name: "toughness",
        type: "fortitude",
        values: [2],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 2,
        splat: ["vampire"],
        error: "You must have at least 2 dot in Fortitude to take this power.",
      },
      {
        name: "enduring beast",
        type: "fortitude",
        values: [2],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 2,
        splat: ["vampire"],
        error: "You must have at least 2 dot in Fortitude to take this power.",
      },
      {
        name: "defy bane",
        type: "fortitude",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dot in Fortitude to take this power.",
      },
      {
        name: "fortify the inner facade",
        type: "fortitude",
        values: [3],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 3,
        splat: ["vampire"],
        error: "You must have at least 3 dot in Fortitude to take this power.",
      },
      {
        name: "draught of endurance",
        type: "fortitude",
        values: [4],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 4,
        splat: ["vampire"],
        error: "You must have at least 4 dot in Fortitude to take this power.",
      },
      {
        name: "flesh of marble",
        type: "fortitude",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dot in Fortitude to take this power.",
      },
      {
        name: "prowess from pain",
        type: "fortitude",
        values: [5],
        check: async (obj: Obj) => (await getStat(obj, "fortitude")) >= 5,
        splat: ["vampire"],
        error: "You must have at least 5 dot in Fortitude to take this power.",
      },
    ],
  },
];
