import "./@js.ts";
import "./alias.ts";
import "./attrCommands.ts";
import "./create.ts";
import "./desc.ts";
import "./format.ts";
import "./help.ts";
import "./lock.ts";
import "./mail.ts";
import "./moniker.ts";
import "./name.ts";
import "./restart.ts";
import "./manipulation.ts";
import "./softcode.ts";
import "./edit.ts";
import "./admin.ts";
import "./search.ts";
import "./messages.ts";

