import { IMStat } from "../../@types";

export const skills: IMStat[] = [
  {
    name: "athletics",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "brawl",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "craft",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "driving",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "firearms",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "larceny",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "melee",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "stealth",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "survival",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "physical",
  },
  {
    name: "animal ken",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "etiquette",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "insight",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "intimidation",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "leadership",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "performance",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "persuasion",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "streetwise",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "subterfuge",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "social",
  },
  {
    name: "academics",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "awareness",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "finance",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "investigation",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "medicine",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "occult",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "politics",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "science",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
  {
    name: "technology",
    values: [0, 1, 2, 3, 4, 5],
    hasSpecialties: true,
    type: "skill",
    default: 0,
    category: "mental",
  },
];
