export interface IPose {
  id: string; // unique id for the pose
  charId: string; // dbref of the character
  charName: string;
  moniker?: string;
  avatar?: string;
  msg: string;
  type: "set" | "pose" | "ooc" | "qs"; // qs = quick start/set context? Ares has different types but pose/ooc is core.
  timestamp: number;
}

export interface IScene {
  id: string; // unique id (autogenerated or number)
  name: string;
  desc?: string;
  owner: string; // dbref of the creator
  location: string; // dbref of the room
  participants: string[]; // dbrefs of characters
  poses: IPose[];
  startTime: number;
  endTime?: number;
  status: "active" | "paused" | "closed";
  private?: boolean;
  allowed?: string[]; // dbrefs of allowed participants
  participantsDetails?: { id: string; name: string; moniker?: string; }[];
  locationDetails?: { name: string; id: string; };
  sceneType?: "social" | "event" | "vignette" | "plot" | "training" | "other" | string;
}
