/**
 * Token helpers — catalog sourced from spec/tokens.json (Phase 0).
 */

import {
  loadTokensFile,
  type TokenDef,
} from "./spec-data.ts";

export type { TokenDef };

/** Sync cache filled by warmTokenCatalog() at server boot. */
let CATALOG: TokenDef[] = [];

/**
 * Populated after warmTokenCatalog(). Prefer ensureTokenCatalog().
 */
export let TOKEN_CATALOG: readonly TokenDef[] = [];

export async function warmTokenCatalog(): Promise<TokenDef[]> {
  const all = await loadTokensFile();
  CATALOG = all.tokens.filter((t) => t.studio !== false);
  TOKEN_CATALOG = CATALOG;
  return CATALOG;
}

export async function ensureTokenCatalog(): Promise<TokenDef[]> {
  if (!CATALOG.length) await warmTokenCatalog();
  return CATALOG;
}

function rootBlock(
  tokens: Record<string, string>,
  scheme: "light" | "dark" | "auto",
): string {
  const catalog = CATALOG;
  const lines: string[] = [":root {"];
  const written = new Set<string>();
  for (const def of catalog) {
    const v = (tokens[def.name] ?? def.default).trim();
    if (!v) continue;
    lines.push(`  ${def.name}: ${v};`);
    written.add(def.name);
  }
  for (const [k, v] of Object.entries(tokens)) {
    if (!k.startsWith("--site-") || written.has(k)) continue;
    const val = String(v).trim();
    if (val) lines.push(`  ${k}: ${val};`);
  }
  if (scheme === "auto") {
    const bg = (tokens["--site-bg"] ?? "").trim();
    lines.push(`  color-scheme: ${isDarkHex(bg) ? "dark" : "light"};`);
  } else {
    lines.push(`  color-scheme: ${scheme};`);
  }
  lines.push("}");
  return lines.join("\n");
}

/**
 * Single-mode CSS from one token map.
 */
export function tokensToCss(
  tokens: Record<string, string>,
  extras = "",
): string {
  const lines: string[] = [
    "/**",
    " * Generated by @ursamu/theme-studio",
    " * Phase 0 token catalog — do not rename .site-* classes.",
    " */",
    "",
    rootBlock(tokens, "auto"),
    "",
  ];
  const extra = extras.trim();
  if (extra) {
    lines.push("/* ── Extra rules (allowlisted selectors) ───────── */");
    lines.push(extra);
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * Dual light/dark export (Phase 5).
 * Light tokens in :root; dark via prefers-color-scheme + [data-theme=dark].
 */
export function tokensToDualCss(
  light: Record<string, string>,
  dark: Record<string, string>,
  extras = "",
): string {
  const darkRoot = rootBlock(dark, "dark");
  const darkBody = darkRoot
    .replace(/^:root\s*\{/, "")
    .replace(/\}\s*$/, "")
    .trim();
  const out: string[] = [
    "/**",
    " * Generated by @ursamu/theme-studio (dual light/dark)",
    " * Toggle: prefers-color-scheme or data-theme=\"dark\"",
    " * on :root / .site-shell",
    " */",
    "",
    rootBlock(light, "light"),
    "",
    "@media (prefers-color-scheme: dark) {",
    darkRoot.split("\n").map((l) => "  " + l).join("\n"),
    "}",
    "",
    ':root[data-theme="dark"],',
    '.site-shell[data-theme="dark"] {',
    darkBody,
    "}",
    "",
  ];
  const extra = extras.trim();
  if (extra) {
    out.push("/* ── Extra rules (allowlisted selectors) ───────── */");
    out.push(extra);
    out.push("");
  }
  return out.join("\n");
}

function isDarkHex(v: string): boolean {
  const m = v.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (!m) return false;
  let h = m[1]!;
  if (h.length === 3) {
    h = h[0]! + h[0] + h[1] + h[1] + h[2] + h[2];
  }
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  const L = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
  return L < 0.45;
}

export function parseRootTokens(css: string): Record<string, string> {
  const out: Record<string, string> = {};
  const m = css.match(/:root\s*\{([\s\S]*?)\}/);
  if (!m) return out;
  const re = /(--site-[\w-]+)\s*:\s*([^;]+);/g;
  let hit: RegExpExecArray | null;
  while ((hit = re.exec(m[1]!)) !== null) {
    out[hit[1]!] = hit[2]!.trim();
  }
  return out;
}

/** CSS after the first :root block (drops preamble comments). */
export function stripRootBlock(css: string): string {
  const m = css.match(/:root\s*\{[\s\S]*?\}/);
  if (!m || m.index === undefined) return css.trim();
  return css.slice(m.index + m[0].length).trim();
}

export function defaultTokenMap(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const def of CATALOG) {
    out[def.name] = def.default;
  }
  return out;
}
