// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $authRouter from "./routes/authRouter.ts";
import * as $buildingRouter from "./routes/buildingRouter.ts";
import * as $config from "./routes/config.ts";
import * as $dbObjRouter from "./routes/dbObjRouter.ts";
import * as $index from "./routes/index.ts";
import * as $sceneRouter from "./routes/sceneRouter.ts";
import * as $wikiRouter from "./routes/wikiRouter.ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/authRouter.ts": $authRouter,
    "./routes/buildingRouter.ts": $buildingRouter,
    "./routes/config.ts": $config,
    "./routes/dbObjRouter.ts": $dbObjRouter,
    "./routes/index.ts": $index,
    "./routes/sceneRouter.ts": $sceneRouter,
    "./routes/wikiRouter.ts": $wikiRouter,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
